  name: Day 3  CI with Env Variables

  on:
    push:
      branches: [main]

  env:
      APP_NAME: cicd-learning
      OWNER: Sandy

  jobs:
    env-demo:
      runs-on: ubuntu-latest
      steps:
        - name: Print Environment Variables
          run: |
            echo "App Name: $APP_NAME"
            echo "Owner: $OWNER"
        - name: Use secret
          run: |
            echo "DB password is ${{ secrets.DB_PASSWORD }}"

