#Day 5 Multiple metrix build and test
name: Day 5 - Multiple Metrics Build and Test
on:
  push:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run : npm install

      - name: Run tests
        run: npm test
