name: Sandy Real CI with Docker

on:
  push:
    branches:
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t sandy-ci-lastet .
